services:
  - type: web
    name: yii2-app-basic
    runtime: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php yii migrate --interactive=0
    startCommand: >
      php -S 0.0.0.0:$PORT -t web/
    env: php
    envVars:
      - key: YII_ENV
        value: prod
    healthCheckPath: /site/health